[profile.default]
solc_version = "0.8.28"
auto_detect_solc = true
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 200
via_ir = true
ffi = true
ast = true
evm_version = "cancun"
build_info = true
extra_output = ["storageLayout"]
[etherscan]
berachain = { key = "${BERASCAN_API_KEY}", url = "https://api.berascan.com/api", chain = 80094 }
bartio = { key = "${BERA_TRAIL_API_KEY}", url = "https://api.routescan.io/v2/network/testnet/evm/80084/etherscan", chain = 80084 }
arbitrum = { key = "${ARBISCAN_API_KEY}", url = "https://api.arbiscan.io/api", chain = 42161 }
arbitrum_sepolia = { key = "${ARBISCAN_API_KEY}", url = "https://api.arbiscan.io/api", chain = 421614 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
